### PR TITLE
implement getSCTLfits and allow for only_PA option in getSCTLfits

### PR DESCRIPTION
**Pull request by FFroehlich**

### CODE REVIEW

**Comment by FFroehlich** [comment]
sorry, forgot to request reviews here and forgot about this :(

**Comment by paulstapor** [comment]
Shouldn't setdefault.m just be the one from PESTO?
On our branch, I implemented the logflag not as boolean, but as string, which can be 'lin', 'log' and 'log10'... How de we handle that? The 'log10' option was helpful for the model coming from D2D, since D2D knows lin and log10...

**Comment by FFroehlich** [comment]
MEMOIR should not deprnd on PESTO.
lin log log10 is probably better

**Comment by paulstapor** [comment]
okay, then it makes sense to have setdefault there. But does getSCTLfits depend on a particular problem? If so, it shouldn't be in the base folder. If not, it shouldn't use PestoOptions()....
I don't think the logflag-divergence has to be changed now, for the master it can stay like it is now. There'll be a more complex merge anyway, when the JAK2/STAT5-thing comes in. This would be a good possibility to go through the changes anyway, also the logflag...

**Comment by FFroehlich** [comment]
getSCTLfits is a general function. It is an auxiliary function that carries out the parameter estimation for all cells individually. As it is not part of the core functionality of MEMOIR, the PESTO dependence is fine.

Merges should always be made as soon as possible in small bits to avoid conflicts.

**Review by paulstapor — APPROVED** [review]
fine

**Pull request merged**
